src/client.rs
This is a bit more performant thanks to collect being optimized.
=> `filter_nones` changed to use combinators

.github/workflows/build.yml, .github/workflows/testing.yml, .gitignore, Cargo.toml, Dockerfile, docker-compose.yaml, examples/ex_1.rs, examples/lowlevel_2.rs, sandbox/bitcoin_dir/bitcoin.conf, sandbox/entrypoint.sh, sandbox/generate-block-bitcoin.sh, sandbox/lightning_dir_one/config, sandbox/lightning_dir_two/config, sandbox/run-bitcoin.sh, sandbox/run-clightning.sh, sandbox/stop-bitcoin.sh, sandbox/stop-clightning.sh, src/client.rs, src/lightningrpc.rs, src/requests.rs, src/responses.rs, tests/rpc_utility_test.rs
This PR it is a draft, and it is a porting of the integration testing made on [JRPClightning](https://github.com/clightning4j/JRPClightning).
What I would like to achieve with this PR is
PS: Sorry if my bitcoin conf is not optimized
Fixes #11
=> Complete test envinroment to run integration testing.

.travis.yml, README.md
=> Repository cleanup

rpc/src/lightningrpc.rs, rpc/src/requests.rs, rpc/tests/rpc_utility_test.rs
At some point we will autogenerate this crate, However, I have not the right tool to make a generation code from a data model!
Fixes https://github.com/laanwj/rust-clightning-rpc/issues/32
=> rpc: update the listinvoices rpc parameters

common/Cargo.toml, common/README.md, rpc/Cargo.toml, rpc/README.md
We prepare to land with the new `common` crate
=> versioning and update readme

common/src/client.rs, common/src/types.rs, plugin/examples/foo_plugin.rs, plugin/src/commands/builtin.rs, plugin/src/commands/mod.rs, plugin/src/macros.rs, plugin/src/plugin.rs, plugin_macros/examples/macros_ex.rs, plugin_macros/src/lib.rs
=> plugin: give the possibility to subscribe to notification

.github/workflows/build.yml, Dockerfile, Makefile, docker-compose.yaml, plugin/Cargo.toml, plugin/src/commands/types.rs, plugin/tests/plugin_integration_test.rs, plugin_macros/Cargo.toml, plugin_macros/examples/macros_ex.rs, plugin_macros/src/lib.rs, plugin_macros/tests/plugin_integration_test.rs, rpc/tests/rpc_utility_test.rs, sandbox/entrypoint.sh, sandbox/lightning_dir_one/config, sandbox/stop-bitcoin.sh, sandbox/stop-clightning.sh
Fixes https://github.com/laanwj/rust-clightning-rpc/issues/37
=> CI: improve integration testing and include the plugin inside it

common/src/types.rs, plugin/examples/foo_plugin.rs, plugin/src/plugin.rs
This fixes a mistake and makes a notification for the log
=> plugin: fix bug in the plugin log rpc call

README.md, docs/MAINTAINERS.md
=> docs: fixes typos

plugin/examples/foo_plugin.rs, plugin/src/commands/builtin.rs, plugin/src/commands/mod.rs, plugin/src/errors.rs, plugin/src/lib.rs, plugin/src/plugin.rs, plugin_macros/Cargo.toml, plugin_macros/examples/macros_ex.rs, plugin_macros/src/lib.rs
Fixes https://github.com/laanwj/rust-clightning-rpc/issues/30
=> Introduce error handling in plugin API

plugin/Cargo.toml, plugin/examples/foo_plugin.rs, plugin/src/commands/builtin.rs, plugin/src/commands/types.rs, plugin/src/lib.rs, plugin/src/plugin.rs, plugin_macros/Cargo.toml
=> feat(plugin): add possibility to register on init

plugin/CHANGELOG.md, plugin/Cargo.toml, plugin/changelog.json
=> plugin: prepare 0.3.0-beta.4

plugin/CHANGELOG.md
=> docs: generate changelog for plugin v0.3.0-rc5

rpc/CHANGELOG.md, rpc/Cargo.toml, rpc/changelog.json
=> rpc: prepare new beta version

README.md, common/README.md, common/src/client.rs, common/src/errors.rs, common/src/lib.rs, common/src/types.rs, plugin/src/commands/builtin.rs, plugin/src/commands/json_utils.rs, plugin/src/commands/mod.rs, plugin/src/commands/types.rs, plugin/src/errors.rs, plugin/src/macros.rs
Better docs and readme.
Will fix #27
=> docs: update docs and readme.

plugin/src/errors.rs
=> fix(plugin): make plugin error API public

Cargo.toml, Makefile, conf/Cargo.toml, conf/README.md, conf/src/file.rs, conf/src/lib.rs, conf/src/parser.rs
Fixes https://github.com/laanwj/cln4rust/issues/70
=> feat(conf): add cln conf parser crate

.github/workflows/build.yml, conf/Cargo.toml, conf/changelog.json, conf/src/lib.rs, conf/src/parser.rs
=> ci: add clippy check inside the CI

conf/CHANGELOG.md
=> docs: generate the changelog for the next tag release

conf/CHANGELOG.md, conf/Cargo.toml, conf/changelog.json, conf/src/lib.rs
=> feat(conf): support field with the same key

plugin/CHANGELOG.md, plugin/Cargo.toml, plugin/changelog.json, plugin/examples/foo_plugin.rs, plugin/src/commands/builtin.rs, plugin/src/commands/types.rs, plugin/src/plugin.rs, plugin/src/types.rs
Fixes https://github.com/laanwj/cln4rust/issues/59
=> feat(plugin): support binding options from init method

conf/src/lib.rs, conf/src/parser.rs
Fixes https://github.com/laanwj/cln4rust/issues/77
=> fix(conf): do not allow duplicate fields

common/src/errors.rs, conf/src/lib.rs, conf/src/parser.rs, plugin/src/plugin.rs, plugin/tests/plugin_integration_test.rs, plugin_macros/tests/plugin_integration_test.rs, rpc/src/lightningrpc.rs, rpc/src/requests.rs, rpc/src/responses.rs, rpc/src/types.rs, rpc/tests/rpc_utility_test.rs
=> some fix for the rpc model

conf/src/lib.rs
This pull request adds a new function `rm_conf` to the `CLNConf` struct, which allows to remove a configuration field from the object. The function takes a key (a string) as input, and returns an error if the key is not present in the object. If the key is present, the function removes the corresponding field and returns `Ok(())`.
I've added a unit test for the `rm_conf` function, which ensures that it behaves as expected when removing a field from the object. The test checks that the field is removed correctly and that the object is flushed to disk as expected.
=> feat(conf): add method to remove a key value pair from the configuration

rpc/src/lightningrpc.rs, rpc/src/requests.rs, rpc/tests/rpc_utility_test.rs
This merges the core commit from https://github.com/laanwj/cln4rust/pull/101
Thank @evd0kim!
=> feat(rpc): added description_hash field

rpc/src/responses.rs
Update satoshi returned values of `pay` command to the doc https://github.com/ElementsProject/lightning/blob/master/doc/lightning-pay.7.md#return-value
=> update msat on Pay response

plugin/src/plugin.rs
Enabling logging for the plugin and be compatible
for cln-plugin.
Fixes: #110
=> feat(plugin): improve the log feature

plugin/src/types.rs
=> fix(plugin): value() now return an option

testing/src/btc.rs
=> testing: bitcoind wait for startup

Makefile, common/src/async.rs, common/src/async/client.rs, rpc/Cargo.toml, rpc/examples/ex_1.rs, rpc/src/async.rs, rpc/src/async/lightningrpc.rs, rpc/src/lib.rs, testing/Cargo.toml, testing/src/cln.rs, tests/Cargo.toml, tests/src/lib.rs, tests/src/test_rpc_async.rs
Fixes: https://github.com/laanwj/cln4rust/issues/1
=> api: implementing async API for RPC
